In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
#no need to dataframe, coz data is already seperated as dep and independent variables

In [2]:
#train and split data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train.shape

(120, 4)

In [3]:
x_test.shape

(30, 4)

In [4]:
from sklearn.svm import SVC

In [5]:
#Linear, RBF, Poly, sigmoid =>Kernel
model=SVC(kernel='rbf') #hyperparameters=> linear,rbf,sigmoid,poly
model.fit(x_train,y_train)

SVC()

In [6]:
y_pred=model.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [7]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [8]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [9]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [10]:
#SVM regression

dataset=pd.read_csv("multisat.csv")
dataset

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [23]:
a=dataset.iloc[:,[0,2]].values
b=dataset.iloc[:,1].values

#train and split data
from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.2,random_state=0)

#
from sklearn.svm import SVR
model_svr=SVR(kernel="linear") #hyperparameters=> linear,rbf,sigmoid,poly
model_svr.fit(a_train,b_train)

SVR(kernel='linear')

In [24]:
model_svr.score(a_train,b_train)

0.41954901687527324

In [25]:
model_svr.score(a_test,b_test)

0.30599904062247996